# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectDevMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ProjectDevMobile

  target 'ProjectDevMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectDevMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ProjectDevMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ProjectDevMobile-tvOS

  target 'ProjectDevMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
